version: '3.7'

services:
  database:
    image: mysql:8.0
    container_name: ix-mysql
    networks:
      - ix_network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 23hx86GQWER4
      MYSQL_DATABASE: ix
    ports:
      - "3306:3306"

#  backend:
#    container_name: ix-backend
#    networks:
#      - ix_network
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - database
#    ports:
#      - "8080:8080"

  backend:
    container_name: ix-backend
    image: ordoghunor/ix-backend:0.2.10
    networks:
      - ix_network
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://ix-mysql:3306/ix
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5000

  prometheus:
    networks:
      - ix_network
    depends_on:
      - backend
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    networks:
      - ix_network
    depends_on:
      - prometheus
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources


networks:
  ix_network:
    driver: bridge
