version: '3.7'

services:
  database:
    image: mysql:8.0
    container_name: mysql
    networks:
      - ix_network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 23hx86GQWER4
      MYSQL_DATABASE: ix
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  ix-spring:
    container_name: ix-spring
    image: docker.io/ordoghunor/ix-spring:0.6.4
    networks:
      - ix_network
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/ix
      - LOGSTASH_HOST=localhost

  prometheus:
    networks:
      - ix_network
    depends_on:
      - ix-spring
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    networks:
      - ix_network
    depends_on:
      - prometheus
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=adminx
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources


networks:
  ix_network:
    driver: bridge
