#az container create --resource-group ix-app-prometheus-grafana --file deployment/azure/aci/aci-manifest-prometheus-grafana.yml
apiVersion: '2018-10-01'
location: westeurope
name: ix-prometheus-grafana
properties:
  containers:
    - name: prometheus
      properties:
        image: prom/prometheus:v2.44.0
        ports:
          - port: 9090
            protocol: TCP
        resources:
          requests:
            cpu: 0.5
            memoryInGB: 1.0
        volumeMounts:
          - name: config-volume
            mountPath: "/etc/prometheus"

    - name: grafana
      properties:
        image: grafana/grafana:9.5.2
        ports:
          - port: 3000
            protocol: TCP
        resources:
          requests:
            cpu: 0.5
            memoryInGB: 1.0
        environmentVariables:
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: adminx
          - name: GF_USERS_ALLOW_SIGN_UP
            value: "false"
          - name: PROMETHEUS_URL
            value: "http://prometheus:9090"

  volumes:
    - name: config-volume
      azureFile:
        shareName: prometheus-config
        storageAccountName: ixprometheusstorage
        storageAccountKey: oooM+nwn5sbLtwsi7Nyka+FVcrjYLUq9cqtiYWAvasiM71YTnwGBExRGser495OoOpNaRSlGFX8C+ASt7njAOg==

  osType: Linux
  ipAddress:
    type: Public
    ports:
      - protocol: TCP
        port: 9090  # Port for Prometheus
      - protocol: TCP
        port: 3000  # Port for Grafana