scrape_configs:
  - job_name: 'ix-app-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['ix-spring:8080']
        labels:
          application: 'My Spring Boot Application'